### ISSUE TITLE
Dúvidas - Seleção Estagiários Optimum Ago/2018 

### ISSUE THREAD

**Issue by robosoptimum** [robosoptimum/estagio_coleta_2018_08#1]
Deixe aqui seu comentário caso tenha dúvidas quanto a realização da tarefa. Responderemos dia 10/08 e a partir do dia 13/08

**Comment by valvesss** [comment]
É possível continuar atualizando o código uma vez que enviado o link?

**Comment by robosoptimum** [comment]
Olá @valvesss . Sim, pode atualizar até na quarta-feira, dia 15, que é o prazo.

**Comment by robosoptimum** [comment]
Envio da tarefa finalizado
